# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb26826aedb499af6c51cbbfe52e38a79bf85c385291ad13d6358e6d9d95fdbcc85b18b9a2e4c32578e0e42cbc9aa88d28d4b5396605a68fa7460bf175f16963

test:
  secret_key_base: f904430b12f60ca08dbbe76cdfa07bc2a9d23dff2aceeb68dca9a58fb1f2b86184237d005986dedd6a8c6ca2f4594141fa4f4dd10ebbca0e7ce3eea4011e9756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
